#!/usr/bin/env python3
from pathlib import Path

path = Path("spike/wasm/build_openrealm_wasm.sh")
text = path.read_text()

anchor = """compile_unity game -DSTB_FDF_IMPLEMENTATION -DSTB_FDF_GLOBALS\ncompile_unity menu -DSTB_FDF_IMPLEMENTATION -DSTB_FDF_GLOBALS\ncompile_unity app\n\n# Copy engine-owned, redistributable config/font assets only. No Warcraft III\n"""
replacement = """compile_unity game -DSTB_FDF_IMPLEMENTATION -DSTB_FDF_GLOBALS\n\n# Compile an unmodified menu probe first so the pinned objects themselves define\n# the namespace boundary. Native OpenRealm loads libgame and libmenu separately;\n# monolithic Wasm must not let duplicate module-private globals/functions alias.\necho \"[wasm:menu-probe]\"\nemcc \"${COMMON_FLAGS[@]}\" \"${PORT_FLAGS[@]}\" \\\n  -DSTB_FDF_IMPLEMENTATION -DSTB_FDF_GLOBALS \\\n  -c build-wasm/unity_menu.c -o build-wasm/obj/menu-probe.o\ncompile_unity app\n\nLLVM_BIN=\"$(cd \"$(dirname \"$(command -v emcc)\")/..\" && pwd)/bin\"\nLLVM_NM=\"$LLVM_BIN/llvm-nm\"\nif [[ ! -x \"$LLVM_NM\" ]]; then\n  echo \"missing LLVM nm required for Wasm module isolation: $LLVM_NM\" >&2\n  exit 3\nfi\n\n\"$LLVM_NM\" -g --defined-only -j build-wasm/obj/game.o | sort -u > build-wasm/game-defined.syms\n\"$LLVM_NM\" -g --defined-only -j build-wasm/obj/menu-probe.o | sort -u > build-wasm/menu-defined.syms\ncomm -12 build-wasm/game-defined.syms build-wasm/menu-defined.syms \\\n  | grep -E '^[A-Za-z_][A-Za-z0-9_]*$' \\\n  > build-wasm/menu-duplicate.syms\n\n# Fail closed if the exact FDF collision family that caused browser menu boot to\n# enter the wrong module is not present in the pinned upstream build.\nfor symbol in frames UI_ParseFDF UI_FdfReadFile UI_LoadTexture Theme_String; do\n  if ! grep -Fxq \"$symbol\" build-wasm/menu-duplicate.syms; then\n    echo \"expected game/menu duplicate missing: $symbol\" >&2\n    exit 4\n  fi\ndone\n\nMENU_NAMESPACE_FLAGS=()\nwhile IFS= read -r symbol; do\n  MENU_NAMESPACE_FLAGS+=(\"-D${symbol}=__openrealm_menu_${symbol}\")\ndone < build-wasm/menu-duplicate.syms\n\n# Recompile only the menu unity with every game/menu duplicate definition in its\n# own namespace. This is the compile-time equivalent of native shared-library\n# isolation and works for Wasm objects where llvm-objcopy cannot rename symbols.\necho \"[wasm:menu-isolated]\"\nemcc \"${COMMON_FLAGS[@]}\" \"${PORT_FLAGS[@]}\" \\\n  \"${MENU_NAMESPACE_FLAGS[@]}\" \\\n  -DSTB_FDF_IMPLEMENTATION -DSTB_FDF_GLOBALS \\\n  -c build-wasm/unity_menu.c -o build-wasm/obj/menu.o\n\n\"$LLVM_NM\" -g --defined-only -j build-wasm/obj/menu.o | sort -u > build-wasm/menu-isolated.syms\nfor symbol in frames UI_ParseFDF UI_FdfReadFile UI_LoadTexture Theme_String; do\n  if grep -Fxq \"$symbol\" build-wasm/menu-isolated.syms; then\n    echo \"menu isolation left critical symbol unnamespaced: $symbol\" >&2\n    exit 5\n  fi\n  if ! grep -Fxq \"__openrealm_menu_${symbol}\" build-wasm/menu-isolated.syms; then\n    echo \"menu isolation lost critical symbol: $symbol\" >&2\n    exit 6\n  fi\ndone\n\nprintf 'OPENREALM_MENU_ISOLATED_SYMBOLS=%s\\n' \"$(wc -l < build-wasm/menu-duplicate.syms)\"\nprintf 'OPENREALM_MENU_ISOLATION_CRITICAL=PASS\\n'\n\n# Copy engine-owned, redistributable config/font assets only. No Warcraft III\n"""
count = text.count(anchor)
if count != 1:
    raise SystemExit(f"build script: expected compile anchor once, got {count}")
text = text.replace(anchor, replacement, 1)

path.write_text(text)
print("OpenRealm menu compile-time namespace patch applied")
