from pathlib import Path
import re

level = Path('src/game/world/Level.ts')
level.write_text('''export interface LevelObstacle {\n  id: number\n  x: number\n  y: number\n  width: number\n  height: number\n}\n\nexport const CITY_LEVEL_OBSTACLES: readonly LevelObstacle[] = [\n  { id: 1, x: -300, y: -155, width: 170, height: 82 },\n  { id: 2, x: -55, y: -160, width: 150, height: 72 },\n  { id: 3, x: 255, y: -150, width: 170, height: 88 },\n  { id: 4, x: -325, y: 18, width: 96, height: 142 },\n  { id: 5, x: 315, y: 22, width: 94, height: 142 },\n  { id: 6, x: -278, y: 163, width: 150, height: 70 },\n  { id: 7, x: 12, y: 168, width: 184, height: 66 },\n  { id: 8, x: 302, y: 166, width: 112, height: 72 },\n] as const\n\nexport function circleOverlapsObstacle(x: number, y: number, radius: number, obstacle: LevelObstacle): boolean {\n  const halfW = obstacle.width / 2\n  const halfH = obstacle.height / 2\n  const closestX = Math.max(obstacle.x - halfW, Math.min(x, obstacle.x + halfW))\n  const closestY = Math.max(obstacle.y - halfH, Math.min(y, obstacle.y + halfH))\n  const dx = x - closestX\n  const dy = y - closestY\n  return dx * dx + dy * dy < radius * radius\n}\n\nexport function pointInsideExpandedObstacle(x: number, y: number, radius: number, obstacle: LevelObstacle): boolean {\n  return x > obstacle.x - obstacle.width / 2 - radius && x < obstacle.x + obstacle.width / 2 + radius && y > obstacle.y - obstacle.height / 2 - radius && y < obstacle.y + obstacle.height / 2 + radius\n}\n''')

kb = Path('src/game/input/KeyboardCombatBuffer.ts')
kb.write_text('''export interface BufferedCombatKeys { slash: boolean; stab: boolean; whirlwind: boolean; dashReleased: boolean }\n\nconst ATTACK_BUFFER_TICKS = 10\nconst WHIRLWIND_BUFFER_TICKS = 12\nconst DASH_RELEASE_BUFFER_TICKS = 12\n\nexport class KeyboardCombatBuffer {\n  private slashTicks = 0\n  private stabTicks = 0\n  private whirlwindTicks = 0\n  private dashReleaseTicks = 0\n  queueSlash(): void { this.slashTicks = ATTACK_BUFFER_TICKS }\n  queueStab(): void { this.stabTicks = ATTACK_BUFFER_TICKS }\n  queueWhirlwind(): void { this.whirlwindTicks = WHIRLWIND_BUFFER_TICKS }\n  queueDashRelease(): void { this.dashReleaseTicks = DASH_RELEASE_BUFFER_TICKS }\n  consume(): BufferedCombatKeys {\n    const value = { slash: this.slashTicks > 0, stab: this.stabTicks > 0, whirlwind: this.whirlwindTicks > 0, dashReleased: this.dashReleaseTicks > 0 }\n    if (this.slashTicks > 0) this.slashTicks -= 1\n    if (this.stabTicks > 0) this.stabTicks -= 1\n    if (this.whirlwindTicks > 0) this.whirlwindTicks -= 1\n    if (this.dashReleaseTicks > 0) this.dashReleaseTicks -= 1\n    return value\n  }\n  clear(): void { this.slashTicks = 0; this.stabTicks = 0; this.whirlwindTicks = 0; this.dashReleaseTicks = 0 }\n}\n''')

p = Path('src/game/sim/GameState.ts')
s = p.read_text()
s = s.replace("import { createImpactProps, type PropMaterial, type PropState } from '../world/Props'\n", "import { createImpactProps, type PropMaterial, type PropState } from '../world/Props'\nimport { CITY_LEVEL_OBSTACLES, circleOverlapsObstacle, pointInsideExpandedObstacle } from '../world/Level'\n")
s = s.replace("export type PowerupKind = 'frenzy' | 'freeze' | 'apple-juice'", "export type PowerupKind = 'last-bite'")
s = s.replace("  | { type: 'flow-freeze'; tick: number; durationTicks: number; source: 'combo' | 'powerup' }\n", "  | { type: 'bullet-time'; tick: number; durationTicks: number }\n  | { type: 'last-chance'; tick: number; powerupId: number; x: number; y: number }\n")
s = s.replace("const FLOW_FREEZE_EVERY_KILLS = 8\nconst FLOW_FREEZE_TICKS = 36\nconst POWERUP_DROP_EVERY_KILLS = 6\nconst POWERUP_TTL_TICKS = 600\nconst POWERUP_PICKUP_RADIUS = 28\nconst FRENZY_TICKS = 360\nconst FRENZY_ATTACK_SPEED = 1.45\nconst POWERUP_FREEZE_TICKS = 90\n", "const LAST_BITE_TTL_TICKS = 240\nconst POWERUP_PICKUP_RADIUS = 30\nconst LAST_CHANCE_BULLET_TIME_TICKS = 150\nconst LAST_CHANCE_WORLD_DIVISOR = 4\nconst LAST_CHANCE_INVULNERABLE_TICKS = 60\nconst LAST_BITE_HEAL = 2\nconst LAST_BITE_FRENZY_TICKS = 120\nconst LAST_BITE_ATTACK_SPEED = 1.25\n")
s = s.replace("  private worldFreezeTicks = 0\n  private frenzyTicks = 0\n", "  private bulletTimeTicks = 0\n  private lastBiteFrenzyTicks = 0\n  private lastChanceUsed = false\n")
old_step = '''    const worldFrozen = this.worldFreezeTicks > 0\n    if (!worldFrozen) {\n      this.updateEnemies()\n      this.resolveEnemyEnemyCollisions()\n      this.resolveEnemyPropCollisions()\n    }\n'''
new_step = '''    const worldStepsThisTick = this.bulletTimeTicks <= 0 || this.tick % LAST_CHANCE_WORLD_DIVISOR === 0\n    if (worldStepsThisTick) {\n      this.updateEnemies()\n      this.resolveEnemyEnemyCollisions()\n      this.resolveEnemyPropCollisions()\n    }\n'''
if old_step not in s: raise SystemExit('world freeze block not found')
s = s.replace(old_step, new_step)
s = s.replace("    if (!worldFrozen) this.resolveEnemyContact()\n", "    if (worldStepsThisTick) this.resolveEnemyContact()\n")
s = s.replace("    if (this.worldFreezeTicks > 0) this.worldFreezeTicks -= 1\n    if (this.frenzyTicks > 0) this.frenzyTicks -= 1\n", "    if (this.bulletTimeTicks > 0) this.bulletTimeTicks -= 1\n    if (this.lastBiteFrenzyTicks > 0) this.lastBiteFrenzyTicks -= 1\n")
s = s.replace("    const comboBoost = this.comboKills >= 12 ? 1.35 : this.comboKills >= 8 ? 1.25 : this.comboKills >= 4 ? 1.12 : 1\n    return comboBoost * (this.frenzyTicks > 0 ? FRENZY_ATTACK_SPEED : 1)\n", "    const comboBoost = this.comboKills >= 12 ? 1.12 : this.comboKills >= 8 ? 1.08 : this.comboKills >= 4 ? 1.04 : 1\n    return comboBoost * (this.lastBiteFrenzyTicks > 0 ? LAST_BITE_ATTACK_SPEED : 1)\n")
s = s.replace("  freezeTicksRemaining(): number {\n    return this.worldFreezeTicks\n  }\n\n  frenzyTicksRemaining(): number {\n    return this.frenzyTicks\n  }\n", "  bulletTimeTicksRemaining(): number { return this.bulletTimeTicks }\n  frenzyTicksRemaining(): number { return this.lastBiteFrenzyTicks }\n  hasUsedLastChance(): boolean { return this.lastChanceUsed }\n")
s = s.replace("    feed(this.worldFreezeTicks)\n    feed(this.frenzyTicks)\n", "    feed(this.bulletTimeTicks)\n    feed(this.lastBiteFrenzyTicks)\n    feed(this.lastChanceUsed ? 1 : 0)\n")
s = s.replace("      feed(powerup.kind === 'frenzy' ? 1 : powerup.kind === 'freeze' ? 2 : 3)\n", "      feed(1)\n")
s = s.replace("    const flowMoveBoost = this.comboMultiplier() >= 3 ? 1.08 : 1\n", "    const flowMoveBoost = this.comboMultiplier() >= 3 ? 1.03 : 1\n")
s = s.replace("    if (!this.playerOverlapsProp(nextX, this.player.y)) this.player.x = nextX\n", "    if (!this.playerOverlapsProp(nextX, this.player.y) && !this.playerOverlapsLevel(nextX, this.player.y)) this.player.x = nextX\n")
s = s.replace("    if (!this.playerOverlapsProp(this.player.x, nextY)) this.player.y = nextY\n", "    if (!this.playerOverlapsProp(this.player.x, nextY) && !this.playerOverlapsLevel(this.player.x, nextY)) this.player.y = nextY\n")
s = s.replace("      this.resolveEnemyArenaWall(enemy)\n      if (!enemy.active) continue\n", "      this.resolveEnemyArenaWall(enemy)\n      this.resolveEnemyLevelObstacles(enemy)\n      if (!enemy.active) continue\n")
s = s.replace("    let blocked = false\n    const dashForce", "    let blocked = false\n    for (const obstacle of CITY_LEVEL_OBSTACLES) {\n      if (!segmentIntersectsExpandedObstacle(startX, startY, endX, endY, PLAYER_RADIUS, obstacle)) continue\n      blocked = true\n      endX = startX\n      endY = startY\n      break\n    }\n    const dashForce")
s = s.replace("    for (const prop of this.props) {\n      if (!prop.active || dash.hitPropIds.includes(prop.id)) continue\n", "    for (const prop of this.props) {\n      if (blocked) break\n      if (!prop.active || dash.hitPropIds.includes(prop.id)) continue\n", 1)
s = re.sub(r"\n    if \(this\.comboKills > 0 && this\.comboKills % FLOW_FREEZE_EVERY_KILLS === 0\) \{.*?\n    \}\n\n    if \(this\.kills % POWERUP_DROP_EVERY_KILLS === 0\) this\.dropPowerup\(x, y\)\n", "\n", s, count=1, flags=re.S)
pattern = r"  private dropPowerup\(x: number, y: number\): void \{.*?\n  \}\n\n  private updatePowerups\(\): void \{.*?\n  \}\n"
replacement = '''  private triggerLastChance(): void {\n    if (this.lastChanceUsed || this.player.hp !== 1) return\n    this.lastChanceUsed = true\n    this.bulletTimeTicks = LAST_CHANCE_BULLET_TIME_TICKS\n    this.player.invulnerableTicks = Math.max(this.player.invulnerableTicks, LAST_CHANCE_INVULNERABLE_TICKS)\n    const angle = normalizeAngle(this.player.facing + Math.PI * 0.5)\n    let x = clamp(this.player.x + Math.cos(angle) * 54, -ARENA_BOUNDS.halfWidth + 24, ARENA_BOUNDS.halfWidth - 24)\n    let y = clamp(this.player.y + Math.sin(angle) * 54, -ARENA_BOUNDS.halfHeight + 24, ARENA_BOUNDS.halfHeight - 24)\n    if (this.playerOverlapsLevel(x, y)) { x = this.player.x; y = this.player.y }\n    const powerup: PowerupState = { id: this.nextPowerupId++, kind: 'last-bite', x, y, active: true, ttlTicks: LAST_BITE_TTL_TICKS }\n    this.powerups.push(powerup)\n    this.events.push({ type: 'last-chance', tick: this.tick, powerupId: powerup.id, x, y })\n    this.events.push({ type: 'powerup-drop', tick: this.tick, powerupId: powerup.id, kind: 'last-bite', x, y })\n    this.events.push({ type: 'bullet-time', tick: this.tick, durationTicks: LAST_CHANCE_BULLET_TIME_TICKS })\n  }\n\n  private updatePowerups(): void {\n    for (const powerup of this.powerups) {\n      if (!powerup.active) continue\n      powerup.ttlTicks -= 1\n      if (powerup.ttlTicks <= 0) { powerup.active = false; continue }\n      const dx = powerup.x - this.player.x\n      const dy = powerup.y - this.player.y\n      if (dx * dx + dy * dy > POWERUP_PICKUP_RADIUS * POWERUP_PICKUP_RADIUS) continue\n      powerup.active = false\n      this.player.hp = Math.min(PLAYER_MAX_HP, this.player.hp + LAST_BITE_HEAL)\n      this.lastBiteFrenzyTicks = LAST_BITE_FRENZY_TICKS\n      this.events.push({ type: 'powerup-picked', tick: this.tick, powerupId: powerup.id, kind: powerup.kind })\n    }\n  }\n'''
s, n = re.subn(pattern, replacement, s, count=1, flags=re.S)
if n != 1: raise SystemExit(f'powerup replacement count={n}')
s = s.replace("      this.events.push({ type: 'player-hit', tick: this.tick, hp: this.player.hp })\n      return\n", "      this.events.push({ type: 'player-hit', tick: this.tick, hp: this.player.hp })\n      this.triggerLastChance()\n      return\n")
marker = "  private resolveEnemyContact(): void {\n"
helpers = '''  private playerOverlapsLevel(x: number, y: number): boolean {\n    return CITY_LEVEL_OBSTACLES.some((obstacle) => circleOverlapsObstacle(x, y, PLAYER_RADIUS, obstacle))\n  }\n\n  private resolveEnemyLevelObstacles(enemy: EnemyState): void {\n    for (const obstacle of CITY_LEVEL_OBSTACLES) {\n      if (!circleOverlapsObstacle(enemy.x, enemy.y, enemy.radius, obstacle)) continue\n      const left = obstacle.x - obstacle.width / 2 - enemy.radius\n      const right = obstacle.x + obstacle.width / 2 + enemy.radius\n      const top = obstacle.y - obstacle.height / 2 - enemy.radius\n      const bottom = obstacle.y + obstacle.height / 2 + enemy.radius\n      const distances = [\n        { axis: 'x' as const, value: left, d: Math.abs(enemy.x - left) },\n        { axis: 'x' as const, value: right, d: Math.abs(enemy.x - right) },\n        { axis: 'y' as const, value: top, d: Math.abs(enemy.y - top) },\n        { axis: 'y' as const, value: bottom, d: Math.abs(enemy.y - bottom) },\n      ].sort((a, b) => a.d - b.d)\n      const escape = distances[0]\n      if (escape.axis === 'x') { enemy.x = escape.value; enemy.impulseX *= -0.18 } else { enemy.y = escape.value; enemy.impulseY *= -0.18 }\n      enemy.staggerTicks = Math.max(enemy.staggerTicks, 2)\n    }\n  }\n\n'''
if marker not in s: raise SystemExit('contact marker missing')
s = s.replace(marker, helpers + marker, 1)
s = s.replace("      if (!this.enemies.spawnAround(this.player.x, this.player.y, this.rng)) break\n", "      const enemy = this.enemies.spawnAround(this.player.x, this.player.y, this.rng)\n      if (!enemy) break\n      if (CITY_LEVEL_OBSTACLES.some((obstacle) => circleOverlapsObstacle(enemy.x, enemy.y, enemy.radius, obstacle))) { this.enemies.kill(enemy); continue }\n")
seg = '''function segmentIntersectsExpandedObstacle(ax: number, ay: number, bx: number, by: number, radius: number, obstacle: { x: number; y: number; width: number; height: number }): boolean {\n  const steps = Math.max(2, Math.ceil(Math.hypot(bx - ax, by - ay) / 8))\n  for (let i = 1; i <= steps; i += 1) {\n    const t = i / steps\n    if (pointInsideExpandedObstacle(ax + (bx - ax) * t, ay + (by - ay) * t, radius, obstacle)) return true\n  }\n  return false\n}\n\n'''
s = s.replace("function clamp(value: number, min: number, max: number): number {\n", seg + "function clamp(value: number, min: number, max: number): number {\n")
p.write_text(s)

p = Path('src/game/scenes/GameScene.ts')
s = p.read_text()
s = s.replace("import { DesktopCombatInput } from '../input/DesktopCombatInput'\n", "import { DesktopCombatInput } from '../input/DesktopCombatInput'\nimport { KeyboardCombatBuffer } from '../input/KeyboardCombatBuffer'\n")
s = s.replace("import type { PropMaterial } from '../world/Props'\n", "import type { PropMaterial } from '../world/Props'\nimport { CITY_LEVEL_OBSTACLES } from '../world/Level'\n")
s = s.replace("  private flowBanner?: Phaser.GameObjects.Text\n", "  private flowBanner?: Phaser.GameObjects.Text\n  private readonly keyboardCombat = new KeyboardCombatBuffer()\n")
s = s.replace("  private queuedSlash = false\n  private queuedStab = false\n  private queuedDashRelease = false\n  private queuedWhirlwind = false\n", "")
s = s.replace("  preload(): void {\n", "  preload(): void {\n    this.load.image('city-tiles', 'assets/levels/city-block/tiles.png')\n    this.load.tilemapTiledJSON('city-level', 'assets/levels/city-block/map.json')\n")
s = s.replace("    this.createArena()\n    this.createPropRenderers()\n", "    this.createArena()\n    this.createImportedCityLevel()\n    this.createPropRenderers()\n")
old = '''    keyboard.on('keydown-SPACE', () => {\n      this.queuedSlash = true\n    })\n    keyboard.on('keydown-E', () => {\n      this.queuedStab = true\n    })\n    keyboard.on('keydown-Q', () => {\n      this.queuedWhirlwind = true\n    })\n    keyboard.on('keyup-SHIFT', () => {\n      this.queuedDashRelease = true\n    })\n'''
new = '''    keyboard.on('keydown-SPACE', (event: KeyboardEvent) => { if (!event.repeat) this.keyboardCombat.queueSlash() })\n    keyboard.on('keydown-E', (event: KeyboardEvent) => { if (!event.repeat) this.keyboardCombat.queueStab() })\n    keyboard.on('keydown-Q', (event: KeyboardEvent) => { if (!event.repeat) this.keyboardCombat.queueWhirlwind() })\n    keyboard.on('keyup-SHIFT', () => this.keyboardCombat.queueDashRelease())\n'''
if old not in s: raise SystemExit('keyboard handler block missing')
s = s.replace(old, new)
old = '''    const mouseAttacks = this.desktopInput.consumeAttacks()\n    const dashHeld = pointer.rightHeld || this.dashKey.isDown\n    const dashReleaseEdge = this.queuedDashRelease || mouseAttacks.dashReleased\n    const input: InputState = {\n      x: Number(this.keys.right.isDown) - Number(this.keys.left.isDown),\n      y: Number(this.keys.down.isDown) - Number(this.keys.up.isDown),\n      slash: this.queuedSlash || mouseAttacks.slash,\n      stab: this.queuedStab,\n      dashHeld,\n      dashReleased: dashReleaseEdge && !dashHeld,\n      whirlwind: this.queuedWhirlwind,\n    }\n'''
new = '''    const mouseAttacks = this.desktopInput.consumeAttacks()\n    const keyAttacks = this.keyboardCombat.consume()\n    const dashHeld = pointer.rightHeld || this.dashKey.isDown\n    const dashReleaseEdge = keyAttacks.dashReleased || mouseAttacks.dashReleased\n    const input: InputState = {\n      x: Number(this.keys.right.isDown) - Number(this.keys.left.isDown),\n      y: Number(this.keys.down.isDown) - Number(this.keys.up.isDown),\n      slash: keyAttacks.slash || mouseAttacks.slash,\n      stab: keyAttacks.stab,\n      dashHeld,\n      dashReleased: dashReleaseEdge && !dashHeld,\n      whirlwind: keyAttacks.whirlwind,\n    }\n'''
if old not in s: raise SystemExit('input block missing')
s = s.replace(old, new)
s = s.replace("\n    this.queuedSlash = false\n    this.queuedStab = false\n    this.queuedDashRelease = false\n    this.queuedWhirlwind = false\n", "")
s = s.replace("      if (event.type === 'flow-freeze') this.showFlowFreeze(event)\n", "      if (event.type === 'bullet-time') this.showBulletTime(event)\n")
s = s.replace("if (this.state.freezeTicksRemaining() > 0) buffs.push(`TIME FROZEN ${(this.state.freezeTicksRemaining() / 60).toFixed(1)}s`)", "if (this.state.bulletTimeTicksRemaining() > 0) buffs.push(`LAST CHANCE ${(this.state.bulletTimeTicksRemaining() / 60).toFixed(1)}s`)")
s = s.replace("private showFlowFreeze(event: Extract<SimEvent, { type: 'flow-freeze' }>): void", "private showBulletTime(event: Extract<SimEvent, { type: 'bullet-time' }>): void")
s = s.replace("'FLOW FREEZE'", "'LAST CHANCE // BULLET TIME'")
s = s.replace("const color = kind === 'frenzy' ? 0xff4f8d : kind === 'freeze' ? 0x8fefff : 0x9ef57d", "const color = 0xffd35a")
s = s.replace("const label = kind === 'frenzy' ? 'CUT' : kind === 'freeze' ? 'TIME' : 'HP'", "const label = 'LAST BITE'")
head_pattern = r"    // Silhouette-first apple head:.*?const leaf = this\.add\.ellipse\(3, -25, 19, 8, green\)\.setStrokeStyle\(2, dark\)\.setRotation\(-0\.48\)\n"
head_repl = '''    // Apple-logo-first top silhouette: smooth lobes, deep cleft, tapered base, oversized side bite.\n    const outline = this.add.graphics()\n    outline.fillStyle(dark, 1)\n    outline.beginPath()\n    outline.moveTo(12, -22)\n    outline.bezierCurveTo(-2, -28, -19, -18, -20, -1)\n    outline.bezierCurveTo(-21, 13, -11, 25, 2, 26)\n    outline.bezierCurveTo(9, 27, 12, 23, 16, 23)\n    outline.bezierCurveTo(20, 23, 28, 17, 29, 7)\n    outline.bezierCurveTo(31, -7, 23, -18, 14, -20)\n    outline.closePath()\n    outline.fillPath()\n    const apple = this.add.graphics()\n    apple.fillStyle(furHighlight, 1)\n    apple.beginPath()\n    apple.moveTo(11, -18)\n    apple.bezierCurveTo(0, -23, -15, -15, -16, -1)\n    apple.bezierCurveTo(-17, 11, -8, 21, 3, 22)\n    apple.bezierCurveTo(9, 23, 12, 19, 16, 19)\n    apple.bezierCurveTo(20, 19, 25, 14, 26, 6)\n    apple.bezierCurveTo(28, -6, 21, -14, 13, -16)\n    apple.closePath()\n    apple.fillPath()\n    const topCleft = this.add.triangle(10, -18, 0, 0, 8, 0, 4, 8, dark).setRotation(Math.PI)\n    const bite1 = this.add.circle(27, -7, 7, dark)\n    const bite2 = this.add.circle(31, 1, 7.5, dark)\n    const bite3 = this.add.circle(27, 9, 6.5, dark)\n    const stem = this.add.rectangle(10, -27, 4, 10, 0x79513a).setRotation(0.24)\n    const leaf = this.add.ellipse(1, -30, 20, 8, green).setStrokeStyle(2, dark).setRotation(-0.48)\n'''
s, n = re.subn(head_pattern, head_repl, s, count=1, flags=re.S)
if n != 1: raise SystemExit(f'head replacement count={n}')
s = s.replace("      headOutline,\n      appleCore,\n      appleTopLobe,\n      appleBottomLobe,\n      appleFront,\n      topCleft,\n      bite1,\n      bite2,\n      bite3,\n", "      outline,\n      apple,\n      topCleft,\n      bite1,\n      bite2,\n      bite3,\n")
marker = "  private createPropRenderers(): void {\n"
method = '''  private createImportedCityLevel(): void {\n    const map = this.make.tilemap({ key: 'city-level' })\n    const tiles = map.addTilesetImage('city-tileset', 'city-tiles', 8, 8, 0, 1)\n    if (tiles) {\n      const x = WORLD_CX - 440\n      const y = WORLD_CY - 240\n      map.createLayer('Terrain', tiles, x, y)?.setScale(2).setAlpha(0.34).setDepth(1)\n      map.createLayer('Objects', tiles, x, y)?.setScale(2).setAlpha(0.58).setDepth(2)\n    }\n    const graphics = this.add.graphics().setDepth(2.5)\n    for (const obstacle of CITY_LEVEL_OBSTACLES) {\n      graphics.fillStyle(0x0c0910, 0.82)\n      graphics.fillRect(WORLD_CX + obstacle.x - obstacle.width / 2, WORLD_CY + obstacle.y - obstacle.height / 2, obstacle.width, obstacle.height)\n      graphics.lineStyle(2, 0x68415f, 0.78)\n      graphics.strokeRect(WORLD_CX + obstacle.x - obstacle.width / 2, WORLD_CY + obstacle.y - obstacle.height / 2, obstacle.width, obstacle.height)\n      graphics.lineStyle(1, 0x3a2638, 0.55)\n      for (let yy = -obstacle.height / 2 + 12; yy < obstacle.height / 2; yy += 18) graphics.lineBetween(WORLD_CX + obstacle.x - obstacle.width / 2 + 8, WORLD_CY + obstacle.y + yy, WORLD_CX + obstacle.x + obstacle.width / 2 - 8, WORLD_CY + obstacle.y + yy)\n    }\n  }\n\n'''
if marker not in s: raise SystemExit('prop marker missing')
s = s.replace(marker, method + marker, 1)
s = s.replace("    this.queuedSlash = false\n    this.queuedStab = false\n    this.queuedDashRelease = false\n    this.queuedWhirlwind = false\n    this.desktopInput.consumeAttacks()\n", "    this.keyboardCombat.clear()\n    this.desktopInput.clearAttackBuffers()\n")
p.write_text(s)

Path('tests/combo-powerups.test.ts').write_text('''import { describe, expect, it } from 'vitest'\nimport { GameState, TARGET_ENEMIES } from '../src/game/sim/GameState'\n\nfunction prepKills(state: GameState, count: number): void {\n  for (const enemy of state.enemies.items) enemy.active = false\n  for (let i = 0; i < count; i += 1) {\n    const enemy = state.enemies.items[i]\n    Object.assign(enemy, { active: true, hp: 1, mass: 1, radius: 10, x: 54 + (i % 3) * 8, y: (i - Math.floor(count / 2)) * 3, speed: 0, vx: 0, vy: 0, impulseX: 0, impulseY: 0, staggerTicks: 0 })\n  }\n}\n\ndescribe('combat reward loop v1', () => {\n  it('keeps the active horde intentionally below 60', () => { expect(TARGET_ENEMIES).toBe(48); expect(new GameState(1).enemies.activeCount()).toBe(48) })\n  it('keeps chain scoring but only modestly accelerates normal cutting', () => {\n    const state = new GameState(2); prepKills(state, 12); state.step({ x: 0, y: 0, aimRadians: 0, whirlwind: true })\n    expect(state.comboMultiplier()).toBe(4); expect(state.attackSpeedMultiplier()).toBeGreaterThan(1); expect(state.attackSpeedMultiplier()).toBeLessThanOrEqual(1.12); expect(state.powerups.filter((powerup) => powerup.active)).toHaveLength(0); expect(state.bulletTimeTicksRemaining()).toBe(0)\n  })\n  it('triggers one last-chance bullet-time rescue when HP falls to one', () => {\n    const state = new GameState(3); for (const enemy of state.enemies.items) enemy.active = false; state.player.hp = 2\n    const enemy = state.enemies.items[0]; Object.assign(enemy, { active: true, hp: 1, mass: 1, radius: 12, x: 0, y: 0, speed: 0, vx: 0, vy: 0, impulseX: 0, impulseY: 0, staggerTicks: 0 })\n    state.step({ x: 0, y: 0 }); expect(state.player.hp).toBe(1); expect(state.hasUsedLastChance()).toBe(true); expect(state.bulletTimeTicksRemaining()).toBeGreaterThan(100); expect(state.powerups.filter((powerup) => powerup.active)).toHaveLength(1); expect(state.events.some((event) => event.type === 'bullet-time')).toBe(true)\n  })\n})\n''')
Path('tests/keyboard-combat-buffer.test.ts').write_text('''import { describe, expect, it } from 'vitest'\nimport { KeyboardCombatBuffer } from '../src/game/input/KeyboardCombatBuffer'\n\ndescribe('keyboard combat buffer', () => {\n  it('holds stab and whirlwind edges across several fixed ticks', () => { const buffer = new KeyboardCombatBuffer(); buffer.queueStab(); buffer.queueWhirlwind(); for (let i = 0; i < 6; i += 1) { const input = buffer.consume(); expect(input.stab).toBe(true); expect(input.whirlwind).toBe(true) } })\n  it('clears all queued edges on restart', () => { const buffer = new KeyboardCombatBuffer(); buffer.queueSlash(); buffer.queueStab(); buffer.queueWhirlwind(); buffer.queueDashRelease(); buffer.clear(); expect(buffer.consume()).toEqual({ slash: false, stab: false, whirlwind: false, dashReleased: false }) })\n})\n''')
Path('tests/level.test.ts').write_text('''import { describe, expect, it } from 'vitest'\nimport { CITY_LEVEL_OBSTACLES, circleOverlapsObstacle } from '../src/game/world/Level'\n\ndescribe('city level geometry', () => { it('provides multiple building blocks and leaves player start open', () => { expect(CITY_LEVEL_OBSTACLES.length).toBeGreaterThanOrEqual(8); expect(CITY_LEVEL_OBSTACLES.some((obstacle) => circleOverlapsObstacle(0, 0, 14, obstacle))).toBe(false) }) })\n''')
Path('docs/RESCUE_LEVEL_V0.md').write_text('''# Rescue + City Level V0\n\nRoutine powerup drops are removed. Combo tiers remain for score, while normal cut-speed bonuses are reduced to 1.04x / 1.08x / 1.12x.\n\nOnce per run, when HP falls to exactly 1, Last Chance fires: enemies/world advance one of every four fixed ticks for 150 ticks (~2.5s), player attacks remain full-rate, the player gets 60 invulnerable ticks, and one nearby LAST BITE pickup appears. LAST BITE heals 2 HP and grants 1.25x cut speed for 120 ticks.\n\nSPACE, E, Q and Shift-release now use fixed-tick buffers matching the responsive mouse input path. Restart clears all buffers.\n\nKenney Pico-8 City CC0 sample map is imported from pinned Tiddybub/2d-assets revision e0cbe0d995554a490d4c182fe9beb8769ffbb606. Its 55x30 8px layout is rendered at 2x under authoritative building collision rectangles, creating streets, alleys and chokepoints.\n''')
